# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0f457317747ecda8b90152fa5406583ddb30f229674ba0d6231ffad3aa483c43c7d5881682f37a6606df8cbd4b73c331b775469ac9216314ea88809660bd439

test:
  secret_key_base: 23a7350d1af5820c1a15484bbea426c297b544a8192f61d17a9eeb4a020d0ec837c423481ce539fbfce04d9dcb30d8bb15571d7088e3813a0c4a4e849368ce57

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
